name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh ubuntu@$EC2_HOST << 'EOF'
            # Navigate to the app directory
            cd ~/CUHackitproject2025/webapp
            
            git pull origin main
            npm ci
            npm run build
            
            # Restart the application (assuming you're using PM2)
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
            
            # Save PM2 configuration
            pm2 save
            
            echo "Deployment completed successfully!"
          EOF
